site_name: Engine User Settings
nav:
  - Home: index.md
  - Setup: setup.md
  - Documentation: documentation.md
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - tables
  - md_in_html
copyright: Copyright &copy; 2023 - 2024 plugin made by Natha Miguel.

cesio137.github.io/
